config/routes.rb
HeroMiles::Application.routes.draw do

  match "/administration" => 'administration#index', :as => 'admin_home'
  match "/administration/applications" => 'administration#applications', :as => 'application_management'
  match '/administration/applications/new' => 'administration#new_application', :as => 'admin_new_application'
  match '/administration/applications/open' => 'administration#show_open'
  match '/administration/applications/notifications' => 'administration#show_notifications'
  match '/administration/applications/:id' => 'administration#show_application', :as => 'admin_show_application'
  match '/administration/organizations' => 'administration#organizations', :as => 'organization_management'
  match '/administration/medical_centers' => 'administration#medical_centers', :as => 'medical_center_management'
  match '/administration/airports' => 'administration#airports', :as => 'airport_management'
  match '/administration/airlines' => 'administration#airlines', :as => 'airline_management'
  match '/administration/groups' => 'administration#groups', :as => 'group_management'
  match '/administration/groups/new' => 'administration#new_group', :as => 'new_group'
  match '/administration/groups/:id/edit' => 'administration#edit_group', :as => 'edit_group'
  match '/administration/groups/:id/mail' => 'administration#mail_group', :as => 'mail_group'
  match '/administration/groups/:id' => 'administration#show_group', :as => 'show_group'
  match '/administration/settings' => 'administration#settings', :as => 'settings'
  match '/administration/attachments' => 'administration#attachments', :as => 'attachments'

  match '/administration/accounts' => 'administration#accounts', :as => 'account_management'
  match '/administration/accounts/pending' => 'administration#show_pending'
  match '/administration/accounts/mail_pending' => 'administration#mail_pending'
  match '/administration/accounts/mail_active' => 'administration#mail_active'
  match '/administration/accounts/active' => 'administration#show_active'
  match '/administration/accounts/new' => 'administration#new_account', :as => 'new_account'
  match '/administration/accounts/:id' => 'administration#show_account', :as => 'account'

  match '/administration/reports' => 'administration#reports', :as => 'report_management'
  match '/administration/advanced' => 'administration#advanced', :as => 'advanced_management'

  match "/case_worker" => 'case_worker#index', :as => 'case_worker_home'

  match '/case_worker/applications' => 'case_worker#applications', :as => 'case_worker_applications'
  match '/case_worker/applications/new' => 'case_worker#new_application', :as => 'case_worker_new_application'
  match '/case_worker/applications/open' => 'case_worker#show_open'
  match '/case_worker/applications/notifications' => 'case_worker#show_notifications'
  match '/case_worker/applications/:id' => 'case_worker#show_application', :as => 'case_worker_show_application'

  match '/case_worker/accounts' => 'case_worker#accounts', :as => 'case_worker_accounts'
  match '/case_worker/reports' => 'case_worker#reports', :as => 'case_worker_reports'
  match '/case_worker/groups' => 'case_worker#groups', :as => 'case_worker_groups'
  match '/case_worker/groups/:id/mail' => 'case_worker#mail_group', :as => 'case_worker_mail_group'
  match '/case_worker/groups/:id' => 'case_worker#show_group', :as => 'case_worker_show_group'

  match '/search/applications' => 'search#applications', :as => 'applications_search'
  match '/search/accounts' => 'search#accounts', :as => 'accounts_search'

  match '/sign_up_confirmation' => 'home#sign_up_confirmation'

  devise_for :users, :controllers => {:registrations => 'registrations',
                                      :sessions => 'sessions' } do
    get 'sign_in', :to => 'sessions#new', :as => 'sign_in'
    get 'sign_out', :to => 'devise/sessions#destroy', :as => 'sign_out'
  end

  resources :users, :path => 'accounts', :only => [:create, :update, :destroy] do
    member do
      post 'approve'
    end
  end

  resources :applications do
    member do
      get 'checkout'
      get 'checkin'
      get 'reopen'
      get 'export'
      post 'mail'
    end
    collection do
      get 'airport'
    end
  end

  resources :application_notes, :only => :create

  resources :organizations, :medical_centers, :airports, :airlines, :groups do
    member do
      post 'archive'
      post 'unarchive'
    end
  end

  resources :app_settings, :only => [:create, :update] do
    collection do
      post 'new_category'
      post 'remove_category'
      post 'update_category'
    end
  end

  match '/reports/summary' => 'reports#summary', :as => 'summary_report'
  match '/reports/monthly' => 'reports#monthly', :as => 'monthly_report'
  match '/reports/branch_airline' => 'reports#branch', :as => 'branch_report'

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_admin!
    if user_signed_in?
      if current_user.is_admin?
        true
      else
        redirect_to '/404'
      end
    else
      redirect_to sign_in_path
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_admin!, :only => [:checkout, :checkin]

  def create
    begin
      @application = Application.process_new params, current_user
      if @application.state == 'saved'
        flash[:notice] = "Application saved successfully"
      elsif @application.state == 'submitted'
        flash[:notice] = "Application submitted successfully"
      elsif @application.state == 'exception'
        flash[:notice] = "Application submitted successfully"
      end
    rescue
      flash[:alert] = AppSettings.invalid_credentials_message
      @application = Application.find_all_by_user_id(current_user.id).last
    end

    if current_user.is_admin?
      redirect_to admin_show_application_path(@application)
    else
      redirect_to case_worker_show_application_path(@application)
    end
  end

  def update
    application_data = params[:application]
    passenger_count = params[:passenger_count].to_i
    passenger_count = 1 if application_data['travellers'] == 'Service Member'

    # Ensure empty passengers aren't created but at the same time
    # existing passengers are deleted when the no. of passengers is reduced.
    passenger_data = application_data.delete 'application_passengers_attributes'

    (0..(AppSettings.first.max_passengers-1)).each do |i|
      if i+1 > passenger_count && passenger_data[i.to_s]['_destroy'] != 'true'
        passenger_data.delete i.to_s
      end
    end

    application_data['application_passengers_attributes'] = passenger_data

    # Remove empty attachments
    unless application_data['attachments_attributes'].blank?
      attachments_data = application_data.delete 'attachments_attributes'
      attachments_data.reject! { |k,v| v['_destroy'] != 'true' && v['document'].blank? }
      application_data['attachments_attributes'] = attachments_data
    end


    if current_user.is_admin?
      # Ensure empty attachments aren't created
      unless application_data['admin_attachments_attributes'].blank?
        attachments_data = application_data.delete 'admin_attachments_attributes'
        attachments_data.reject! { |k,v| v['_destroy'] != 'true' && v['document'].blank? }
        application_data['admin_attachments_attributes'] = attachments_data
      end


      # Ensure empty flights aren't created but at the same time
      # existing flights are deleted when the no. of flights is reduced.
      outbound_flight_count = params[:outbound_flight_count].to_i
      outbound_flight_data = application_data.delete 'outbound_flights_attributes'

      if outbound_flight_data
        (0..(AppSettings.first.max_flights-1)).each do |i|
          if i+1 > outbound_flight_count && outbound_flight_data[i.to_s] && outbound_flight_data[i.to_s]['_destroy'] != 'true'
            outbound_flight_data.delete i.to_s
          end
        end
        application_data['outbound_flights_attributes'] = outbound_flight_data
        (0...outbound_flight_count).each do |i|
          application_data['outbound_flights_attributes'][i.to_s]["depart_time"] = ""  if application_data['outbound_flights_attributes'][i.to_s]["depart_time"].length < 7
          application_data['outbound_flights_attributes'][i.to_s]["arrive_time"] = "" if application_data['outbound_flights_attributes'][i.to_s]["arrive_time"].length < 7
        end
      end

      if outbound_flight_count >= 1
        application_data['final_departure_date(1i)'] = application_data['outbound_flights_attributes'][0.to_s]["departure_date(1i)"]
        application_data['final_departure_date(2i)'] = application_data['outbound_flights_attributes'][0.to_s]["departure_date(2i)"]
        application_data['final_departure_date(3i)'] = application_data['outbound_flights_attributes'][0.to_s]["departure_date(3i)"]
      end

      return_flight_count = params[:return_flight_count].to_i
      return_flight_data = application_data.delete 'return_flights_attributes'
      if return_flight_data
        (0..(AppSettings.first.max_flights-1)).each do |i|
          if i+1 > return_flight_count && return_flight_data[i.to_s] && return_flight_data[i.to_s]['_destroy'] != 'true'
            return_flight_data.delete i.to_s
          end
        end
        application_data['return_flights_attributes'] = return_flight_data
        (0...return_flight_count).each do |i|
          application_data['return_flights_attributes'][i.to_s]["depart_time"] = ""  if application_data['return_flights_attributes'][i.to_s]["depart_time"].length < 7
          application_data['return_flights_attributes'][i.to_s]["arrive_time"] = "" if application_data['return_flights_attributes'][i.to_s]["arrive_time"].length < 7
        end
      end

      if return_flight_count >= 1
        application_data['final_return_date(1i)'] = application_data['return_flights_attributes'][0.to_s]["departure_date(1i)"]
        application_data['final_return_date(2i)'] = application_data['return_flights_attributes'][0.to_s]["departure_date(2i)"]
        application_data['final_return_date(3i)'] = application_data['return_flights_attributes'][0.to_s]["departure_date(3i)"]
      end

      @application = Application.find_by_id params[:id]
      @application.assign_attributes application_data, :as => :admin
    else
      @application = current_user.applications.find_by_id params[:id]
      @application.assign_attributes application_data
    end

    begin
      if params[:commit] == 'Save'
        @application.is_exception = true unless @application.valid?
        @application.save && @application.save_application!(:user => current_user)
        flash[:notice] = "Application saved successfully"
      elsif current_user.is_admin?
        @application.save
        if params[:commit] == 'Update'
          flash[:notice] = "Application updated successfully"
        elsif params[:commit] == 'Submit'
          @application.submit!(:user => current_user)
          flash[:notice] = "Application submitted successfully"
        elsif params[:commit] == 'Return'
          @application.return!(:user => current_user)
          flash[:notice] = "Application returned successfully"
        elsif params[:commit] == 'Decline'
          @application.decline!(:user => current_user)
          flash[:notice] = "Application declined successfully"
        elsif params[:commit] == 'Complete'
          @application.complete!(:user => current_user, :exception => params[:exception_reason])

          ticket = render_to_string :pdf => 'TicketTopper',
                                    :layout => 'pdf',
                                    :template => 'applications/ticket_topper.pdf.haml',
                                    :margin => {:bottom => 30},
                                    :footer => {:html => {:template => 'applications/_ticket_topper_footer.pdf.haml'}}

          tf = Tempfile.new "Itinerary.pdf"
          tf.binmode
          tf << ticket
          tf.flush && tf.rewind

          begin
            @application.email_itinerary(tf)
          rescue
            flash[:alert] = "Could not deliver notification email to #{@application.created_by_admin?? "Administrator" : "Case Worker"} because of  blank #{@application.created_by_admin?? "Administrator" : "Case Worker"} E-mail address."
          end

          flash[:notice] = "Application completed successfully"
        elsif params[:commit] == 'Save Changes'
          flash[:notice] = "Application saved successfully"
        else
          @application.is_exception = false
          if @application.valid?
            @application.save && @application.submit!(:user => current_user)
          else
            @application.is_exception = true
            @application.save && @application.raise_exception!(:user => current_user, :exception => params[:exception_reason])
          end
          flash[:notice] = "Application submitted successfully"
        end
      else
        @application.is_exception = false
        if @application.valid?
          @application.save && @application.submit!(:user => current_user)
        else
          @application.is_exception = true
          @application.save && @application.raise_exception!(:user => current_user, :exception => params[:exception_reason])
        end
        flash[:notice] = "Application submitted successfully"
      end
      unless flash[:alert].nil?
        flash[:notice] = nil
      end
    rescue
      flash[:alert] = AppSettings.invalid_credentials_message
    end

    if current_user.is_admin?
      redirect_to admin_show_application_path(@application)
    else
      redirect_to case_worker_show_application_path(@application)
    end
  end

  def destroy
    @application = Application.find_by_id params[:id]
    redirect_to '/404' and return unless @application

    if @application.user == current_user && ['saved', 'returned'].include?(@application.state)
      @application.destroy
      flash[:notice] = "Application deleted successfully"
    end

    redirect_to( current_user.is_admin? ? application_management_path : case_worker_applications_path)
  end

  def checkout
    @application = Application.find_by_id params[:id]
    if params[:user].blank?
      @application.checkin!(current_user)
      flash[:notice] = "Application Unassigned successfully"
      redirect_to application_management_path and return
    else
      @user = User.find_by_id params[:user]
      @application.checkout!(@user) if @user.is_admin?
    end
    redirect_to '/404' and return unless @application
    redirect_to admin_show_application_path(@application)
  end

  def checkin
    @application = Application.find_by_id params[:id]
    redirect_to '/404' unless @application
    @application.checkin!(current_user)
    redirect_to admin_show_application_path(:id => @application.id, :checkout => 'false')
  end

  def reopen
    @application = Application.find_by_id params[:id]
    redirect_to '/404' unless @application
    begin

app/helpers/application_helper.rb
module ApplicationHelper
  def page_entries_info(collection, options = {})
    collection_name = options[:collection_name] || (collection.empty?? 'entry' : collection.first.class.name.underscore.sub('_', ' '))
    if collection.num_pages < 2
      case collection.size
      when 0; info = "No #{collection_name.pluralize} found"
      when 1; info = "Displaying <strong>1</strong> #{collection_name}"
      else;   info = "Displaying <strong>all #{collection.size}</strong> #{collection_name.pluralize}"
      end
    else
      start = collection.per_page * (collection.current_page - 1) + 1
      info = %{Displaying #{collection_name.pluralize} <strong>%d&ndash;%d</strong> of <strong>%d</strong> in total}% [
        start,
        start + collection.length - 1,
        collection.total_entries
      ]
    end
    info.html_safe
  end

  def available_us_states
    Carmen.states + [['International', 'International']]
  end

end

app/helpers/applications_helper.rb
module ApplicationsHelper

  def time_select_12_hour
  end

end

app/views/applications/_admin_buttons.html.haml
.buttons
  - if a.object.persisted? && !['saved', 'returned'].include?(a.object.state)
    - if a.object.is_editable?(current_user)
      %a.complete-button.button{:href => '#', :title => 'Complete Application'} Complete
      = a.submit 'Complete', :class => 'hidden', :id => 'complete-form'
      = a.submit 'Decline', :class => 'button', :title => 'Decline Application'
      = a.submit 'Return', :class => 'button', :title => 'Return application to caseworker for revision'
      %span{:class => 'buttons-divider'}
      = a.submit 'Save Changes', :class => 'button', :title => 'Save changes to application'

    - elsif ['completed', 'declined'].include?(a.object.state) && a.object.admin == current_user
      = link_to 'Reopen', reopen_application_path(a.object), :confirm => 'Are you sure you wish to Reopen this application for editing or a status change? Reopening will cause a change to the completion date.', :class => 'button'
    - if a.object.admin && a.object.admin == current_user
      %a.add-note-button.button{:href => '#' } Add a note
  - else
    - if a.object.user == current_user
      = a.submit 'Save', :class => 'button'
      %a.submit-button.button{:href => '#'} Submit
      = a.submit 'Submit', :class => 'hidden', :id => 'submit-form'
      - if ['saved', 'returned'].include?(a.object.state) && a.object.is_editable?(current_user)
        = link_to 'Delete', application_path(a.object), :method => :delete, :confirm => 'Are you sure you want to delete this application?', :class => 'button', :title => 'Delete application'

  %br
  %br

  - if a.object.persisted? # && a.object.state != 'saved'
    %a.export-button.button{:href => '#' } View/Print/Save
    %a.email-button.button{:href => '#' } Email
  - if ['completed', 'submitted', 'exception', 'reopened', 'declined', ].include?(a.object.state)#a.object.is_checked_out?
    %span{:class => 'buttons-divider'}
    %a#assign_button.button{:href => checkout_application_path(:id => a.object.id, :user => current_user.id)} Assign To
    = select_tag :assign_to, options_for_select([['Unassigned','']] + User.admin.collect{ |x| [x.full_name, x.id]}, current_user.id)
    (currently #{a.object.admin.blank?? 'Unassigned' : a.object.admin.full_name})

  %br
  %br

app/views/applications/_form.html.haml
- template ||= false
- template_fields ||= []
- @hide_cw ||= false
- @hide_admin ||= false
- if @application.group && !template
  - fields = @application.group.fields
- else
  - fields = []

#no-back
  %a{:class => @application.persisted?? '': 'hidden' }

#application-form

  = form_for @application, :html => {:class => 'bp'} do |a|
    = hidden_field_tag :exception_reason
    - @editable ||= a.object.is_editable?(current_user)
    - if current_user.is_admin? && !template
      #application-tabs
        %ul
          %li
            %a{:href => '#case-worker-section'} Case Worker View
          %li
            %a{:href => '#admin-section'} Admin View

        #case-worker-section
          = render :partial => 'applications/case_worker_form', :locals => { :a => a, :editable => @editable, :fields => fields }
          -# = render :partial => 'applications/admin_buttons', :locals => {:a => a}


        #admin-section
          - if a.object.persisted?
            = render :partial => 'applications/admin_form', :locals => {:a => a, :editable => @editable}
          - else
            %h4 Please submit the application first to proceed.
        .application-buttons
          = render :partial => 'applications/admin_buttons', :locals => {:a => a}

    - else
      = render :partial => 'applications/case_worker_form', :locals => { :a => a, :template => template, :template_fields => template_fields, :fields => fields }
      - unless template
        .buttons
          - if a.object.is_editable?(current_user)
            = a.submit 'Save', :class => 'button'
            %a#submit-button.button{:href => '#'} Submit
            = a.submit 'Submit', :class => 'hidden', :id => 'submit-form'
          - elsif a.object.user.id == current_user.id
            %a#add-note-button.button{:href => '#'} Add a Note

          - if a.object.persisted?
            - if ['saved', 'returned'].include?(a.object.state) && a.object.user.id == current_user.id
              = link_to 'Delete', application_path(a.object), :method => :delete, :confirm => 'Are you sure you want to delete this application?', :class => 'button', :title => 'Delete application'
            %a#export-button.button{:href => case_worker_show_application_path(a.object, :pdf)} View/Print/Save


#hidden
  #exception-dialog
    %h3 The following fields are incomplete:

    %ul#exception-list

    %p You can either submit the application after completing the above fields or request an exception.

    .buttons
      %a#request-exception-button.button{:href => '#'} Request Exception
      %a#complete-fields-button.button{:href => '#'} Complete empty fields

    #exception-reason.hidden
      %h4 Why are you requesting an exception?
      = form_tag '/', :id => 'exception_form' do
        = text_area_tag :exception_text, '', :class => 'validate[required]'
      %a#submit-exception-button.button{:href => '#'} Submit


  #add-note-dialog
    = form_for ApplicationNote.new, :html => {:class => 'bp validate'}, :remote => true do |n|
      = n.hidden_field :application_id, :value => @application.id
      = n.hidden_field :user_id, :value => current_user.id


      %div
        = n.label :message, 'Note:'
        %br
        = n.text_area :message, :class => 'validate[required]'

      .buttons
        = n.submit 'Add', :class => 'button'

  - if @application.persisted?
    #export-dialog
      %table
        %tbody
          %tr
            %td Application - Case Worker Sections
            %td
              %a{:href => "/applications/#{@application.id}/export?cw_application=true&view=true"} view
            %td
              %a{:href => "/applications/#{@application.id}/export?cw_application=true&save=true"} save

          - if current_user.is_admin? && !['new', 'saved'].include?(@application.state)
            %tr
              %td Application - Administrator Sections
              %td
                %a{:href => "/applications/#{@application.id}/export?admin_application=true&view=true"} view
              %td
                %a{:href => "/applications/#{@application.id}/export?admin_application=true&save=true"} save

          - if @application.state == 'completed'
            %tr
              %td Ticket Topper
              %td
                %a{:href => "/applications/#{@application.id}/export?itinerary=true&view=true"} view
              %td
                %a{:href => "/applications/#{@application.id}/export?itinerary=true&save=true"} save

          - @application.attachments.select{|x| x.document_content_type == 'application/pdf'}.each do |at|
            - unless at.document_file_name.blank?
              %tr
                %td #{at.document_file_name} (Attachment)
                %td
                  %a{:href => "/applications/#{@application.id}/export?attachment=#{at.id}&view=true"} view
                %td
                  %a{:href => "/applications/#{@application.id}/export?attachment=#{at.id}&save=true"} save

          - @application.admin_attachments.select{|x| x.document_content_type == 'application/pdf'}.each do |at|
            - unless at.document_file_name.blank?
              %tr
                %td #{at.document_file_name} (Attachment)
                %td
                  %a{:href => "/applications/#{@application.id}/export?admin_attachment=#{at.id}&view=true"} view
                %td
                  %a{:href => "/applications/#{@application.id}/export?admin_attachment=#{at.id}&save=true"} save
      %p To print, view the file and select Print from the File menu.

    #email-dialog
      = form_tag mail_application_path(@application), :class => 'bp validate' do
        %p.attachments
          %p
            = check_box_tag :cw_application, 'true', true, :class => 'validate[group-attach] group-attach'
            = label_tag :cw_application, 'Application - Case Worker Sections'

          - if current_user.is_admin? && !['new', 'saved'].include?(@application.state)
            %p
              = check_box_tag :admin_application, 'true', true, :class => 'validate[group-attach] group-attach'
              = label_tag :admin_application, 'Application - Administrator Sections'

          - if @application.state == 'completed'
            %p
              = check_box_tag :itinerary, 'true', true, :class => 'validate[group-attach] group-attach'
              = label_tag :itinerary, 'Itinerary'

          - @application.attachments.select{|x| x.document_content_type == 'application/pdf'}.each do |at|
            - unless at.document_file_name.blank?
              %p
                = check_box_tag "email_attachment_#{at.id}", "true", true, :name => "attachments[#{at.id}]", :class => 'validate[group-attach] group-attach'
                = label_tag "email_attachment_#{at.id}", "#{at.document_file_name} (Attachment)"

          - if current_user.is_admin?
            - @application.admin_attachments.each do |at|
              - unless at.document_file_name.blank?
                %p
                  = check_box_tag "email_attachment_#{at.id}", "true", true, :name => "attachments[#{at.id}]", :class => 'validate[group-attach] group-attach'
                  = label_tag "email_attachment_#{at.id}", "#{at.document_file_name} (Attachment)"

        %p.email_to
          Email To:
          %br

          - unless @application.case_worker_email.blank?
            %p
              = check_box_tag :email_caseworker, 'true', true, :name => 'email_caseworker', :class => 'validate[group-email] group-email'
              = label_tag :email_caseworker, @application.case_worker_email


          - unless @application.email.blank?
            %p
              = check_box_tag :email_service_member, 'true', true, :name => 'email_service_member', :class => 'validate[group-email] group-email'
              = label_tag :email_service_member, @application.email


          %p
            = check_box_tag :email_other, 'true', false, :name => 'email_other', :class => 'validate[group-email] group-email'
            = label_tag :email_other, 'Email another person:'
            = text_field_tag :email_other_address, '', :class => 'validate[email]', :disabled => true

        = submit_tag 'Email', :class => 'button'

app/views/applications/_form.pdf.haml
- template ||= false
- template_fields ||= []
- if @application.group
  - fields = @application.group.fields
- else
  - fields = []

- @hide_cw ||= false
- @hide_admin ||= false

#application-form

  = form_for @application, :html => {:class => 'bp'} do |a|
    - @editable = false
    - if current_user.is_admin? && !template
      #application-tabs

        - unless @hide_cw
          .page-title Hero Miles Application - Case Worker Sections
          #case-worker-section
            = render :partial => 'applications/case_worker_form', :locals => { :a => a, :editable => @editable, :fields => fields }

        - unless @hide_admin
          .page-title Hero Miles Application - Administrator Sections
          #admin-section
            - if a.object.persisted?
              = render :partial => 'applications/admin_form', :locals => {:a => a, :editable => @editable}
            - else
              %h4 Please submit the application first to proceed.


    - else
      = render :partial => 'applications/case_worker_form', :locals => { :a => a, :template => template, :template_fields => template_fields, :fields => fields }

app/views/applications/_ticket_topper_footer.pdf.haml
.tag-line{:style => 'text-align: right;font-weight: bold;font-family: "LiberationSerif", serif;'}
  Program of the Fisher House Foundation
  = wicked_pdf_image_tag 'itinerary-logo.gif', :width => '75', :height => '75'

app/views/applications/ticket_topper.pdf.haml
#ticket-topper

  .logo
    %div
      = wicked_pdf_image_tag 'itinerary_header_logo.jpg', :width => '436', :height => '102'
    - if !@application.airline.blank? && File.exist?("#{Rails.root}/app/assets/images/#{@application.airline.parameterize}.gif")
      %div
        = wicked_pdf_image_tag "#{@application.airline.parameterize}.gif"


  .page-heading ARRIVE/CHECK-IN EARLY FOR SEATING
  .page-heading PASSENGER IS RESPONSIBLE FOR BAGGAGE FEES INCURRED

  %table#details
    %tbody
      %tr.record
        %td Record Locator
        %td= @application.record_locator

      %tr
      %tr.blue
        %td Passenger
        %td Ticket Number

      - @application.application_passengers.each do |ap|
        %tr
          %td= ap.name.gsub(/\b('?[a-z])/) { $1.capitalize }
          %td= ap.ticket_no

  %p.left.blue Flight Information

  %table#flight-info
    %thead
      %tr
        %td Day
        %td Date
        %td Flight
        %td City
        %td Time
        %td Seat

    %tbody
      - @application.outbound_flights.each do |af|
        %tr
          %td= af.departure_date.strftime "%A" unless af.departure_date.blank?
          %td= af.departure_date.strftime "%d %B" unless af.departure_date.blank?
          %td= af.flight_no
          %td
            LV #{af.depart_from}
            %br
            AR #{af.arrive_in}
            %br
          %td
            = af.formatted_departure_time
            %br
            = af.formatted_arrival_time
            %br
          %td
            = af.formatted_seats
      %tr
        %td
          %br

      %tr
        %td
          %br

      - @application.return_flights.each do |af|
        %tr
          %td= af.departure_date.strftime "%A" unless af.departure_date.blank?
          %td= af.departure_date.strftime "%d %B" unless af.departure_date.blank?
          %td= af.flight_no
          %td
            LV #{af.depart_from}
            %br
            AR #{af.arrive_in}
            %br
          %td
            = af.formatted_departure_time
            %br
            = af.formatted_arrival_time
            %br
          %td
            = af.formatted_seats