config/routes.rb
HeroMiles::Application.routes.draw do

  match "/administration" => 'administration#index', :as => 'admin_home'
  match "/administration/applications" => 'administration#applications', :as => 'application_management'
  match '/administration/applications/new' => 'administration#new_application', :as => 'admin_new_application'
  match '/administration/applications/open' => 'administration#show_open'
  match '/administration/applications/notifications' => 'administration#show_notifications'
  match '/administration/applications/:id' => 'administration#show_application', :as => 'admin_show_application'
  match '/administration/organizations' => 'administration#organizations', :as => 'organization_management'
  match '/administration/medical_centers' => 'administration#medical_centers', :as => 'medical_center_management'
  match '/administration/airports' => 'administration#airports', :as => 'airport_management'
  match '/administration/airlines' => 'administration#airlines', :as => 'airline_management'
  match '/administration/groups' => 'administration#groups', :as => 'group_management'
  match '/administration/groups/new' => 'administration#new_group', :as => 'new_group'
  match '/administration/groups/:id/edit' => 'administration#edit_group', :as => 'edit_group'
  match '/administration/groups/:id/mail' => 'administration#mail_group', :as => 'mail_group'
  match '/administration/groups/:id' => 'administration#show_group', :as => 'show_group'
  match '/administration/settings' => 'administration#settings', :as => 'settings'
  match '/administration/attachments' => 'administration#attachments', :as => 'attachments'

  match '/administration/accounts' => 'administration#accounts', :as => 'account_management'
  match '/administration/accounts/pending' => 'administration#show_pending'
  match '/administration/accounts/mail_pending' => 'administration#mail_pending'
  match '/administration/accounts/mail_active' => 'administration#mail_active'
  match '/administration/accounts/active' => 'administration#show_active'
  match '/administration/accounts/new' => 'administration#new_account', :as => 'new_account'
  match '/administration/accounts/:id' => 'administration#show_account', :as => 'account'

  match '/administration/reports' => 'administration#reports', :as => 'report_management'
  match '/administration/advanced' => 'administration#advanced', :as => 'advanced_management'

  match "/case_worker" => 'case_worker#index', :as => 'case_worker_home'

  match '/case_worker/applications' => 'case_worker#applications', :as => 'case_worker_applications'
  match '/case_worker/applications/new' => 'case_worker#new_application', :as => 'case_worker_new_application'
  match '/case_worker/applications/open' => 'case_worker#show_open'
  match '/case_worker/applications/notifications' => 'case_worker#show_notifications'
  match '/case_worker/applications/:id' => 'case_worker#show_application', :as => 'case_worker_show_application'

  match '/case_worker/accounts' => 'case_worker#accounts', :as => 'case_worker_accounts'
  match '/case_worker/reports' => 'case_worker#reports', :as => 'case_worker_reports'
  match '/case_worker/groups' => 'case_worker#groups', :as => 'case_worker_groups'
  match '/case_worker/groups/:id/mail' => 'case_worker#mail_group', :as => 'case_worker_mail_group'
  match '/case_worker/groups/:id' => 'case_worker#show_group', :as => 'case_worker_show_group'

  match '/search/applications' => 'search#applications', :as => 'applications_search'
  match '/search/accounts' => 'search#accounts', :as => 'accounts_search'

  match '/sign_up_confirmation' => 'home#sign_up_confirmation'

  devise_for :users, :controllers => {:registrations => 'registrations',
                                      :sessions => 'sessions' } do
    get 'sign_in', :to => 'sessions#new', :as => 'sign_in'
    get 'sign_out', :to => 'devise/sessions#destroy', :as => 'sign_out'
  end

  resources :users, :path => 'accounts', :only => [:create, :update, :destroy] do
    member do
      post 'approve'
    end
  end

  resources :applications do
    member do
      get 'checkout'
      get 'checkin'
      get 'reopen'
      get 'export'
      post 'mail'
    end
    collection do
      get 'airport'
    end
  end

  resources :application_notes, :only => :create

  resources :organizations, :medical_centers, :airports, :airlines, :groups do
    member do
      post 'archive'
      post 'unarchive'
    end
  end

  resources :app_settings, :only => [:create, :update] do
    collection do
      post 'new_category'
      post 'remove_category'
      post 'update_category'
    end
  end

  match '/reports/summary' => 'reports#summary', :as => 'summary_report'
  match '/reports/monthly' => 'reports#monthly', :as => 'monthly_report'
  match '/reports/branch_airline' => 'reports#branch', :as => 'branch_report'

  root :to => 'home#index'

end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  before_filter :authenticate_admin!

  def index
    redirect_to application_management_path
  end

  def applications
    @open = Application.admin_open(current_user).order("-departure_date desc")
    @notifications = Application.admin_notification_messages(current_user).order("last_cw_note_date asc")
    #@notifications += Application.admin_notification_completed(current_user).order("updated_at desc").limit(6-@notifications.size)
    #@notifications.flatten!
  end

  def new_application
    if params[:group]
      @group = Group.find_by_id params[:group]
    end
    @application = Application.new :user => current_user, :organization => current_user.organization
    if @group
      @application.group = @group
      @application.set_group_defaults
    end
    @application.set_cw_details
    @application.created_by_admin = true
    AppSettings.first.max_passengers.times { |x| @application.application_passengers.build }
    AppSettings.first.max_flights.times { |x| @application.outbound_flights.build }
    AppSettings.first.max_flights.times { |x| @application.return_flights.build }
    AppSettings.attachment_categories.select { |x| x['cw'] && x['admin'] && x['required'] && !x['is_archived'] }.each do |ac|
      @application.attachments.build :is_cw => true,
                                     :is_admin => true,
                                     :is_required => true,
                                     :category => ac['name'],
                                     :ref_id => ac['id']
    end
    @medical_centers = MedicalCenter.sorted
    @organizations = Organization.sorted
  end

  def show_application
    @application = Application.find_by_id params[:id]
    (redirect_to '/404' and return) unless @application

    @editable = @application.is_editable?(current_user)
    unless params[:checkout] == 'false' || !@editable
      @application.checkout!(current_user) if @application.admin.blank?
    end

    if @editable
      (AppSettings.first.max_flights - @application.outbound_flights.size).times { |x| @application.outbound_flights.build}
      (AppSettings.first.max_flights - @application.return_flights.size).times { |x| @application.return_flights.build}
      (AppSettings.first.max_passengers - @application.application_passengers.size).times { |x| @application.application_passengers.build}
      AppSettings.attachment_categories.select { |x| x['cw'] && x['admin'] && x['required'] && !x['is_archived'] }.each do |ac|
        attachment = @application.attachments.find_by_ref_id ac['id']
        if attachment.blank? && !ac['is_archived']
          @application.attachments.build :is_cw => true,
                                         :is_admin => true,
                                         :is_required => true,
                                         :category => ac['name'],
                                         :ref_id => ac['id']
        end
      end

      AppSettings.attachment_categories.select { |x| !x['cw'] && x['admin'] && x['required'] && !x['is_archived'] }.each do |ac|
        attachment = @application.admin_attachments.find_by_ref_id ac['id']
        if attachment.blank? && !ac['is_archived']
          @application.admin_attachments.build :is_admin => true,
                                               :is_required => true,
                                               :category => ac['name'],
                                               :ref_id => ac['id'],
                                               :owned_by_admin => true
        end
      end
    end

    @medical_centers = ([MedicalCenter.unscoped.find_by_id(@application.medical_center_id)] + MedicalCenter.sorted).flatten.uniq.compact
    @organizations = ([Organization.unscoped.find_by_id(@application.organization_id)] + Organization.sorted).flatten.uniq.compact

    respond_to do |f|
      f.html
      f.pdf { render :pdf => "Application-#{@application.id}", :layout => 'pdf'}
    end
  end

  def accounts
    @active = User.active.order('first_name asc')
    @pending = User.inactive.order('first_name asc')
  end

  def show_account
    @user = User.find_by_id params[:id]
    (redirect_to '/404' and return) unless @user
  end

  def new_account
    @user = User.new
  end

  def show_pending
    @accounts = User.where(:expires_at => nil, :is_active => false).order('first_name asc')
    respond_to do |f|
      f.html
      f.pdf do
        render :pdf => "PendingAccounts", :layout => 'pdf'
      end
    end
  end

  def show_active
    @accounts = User.where(:is_active => true).order('first_name asc')
    respond_to do |f|
      f.html
      f.pdf do
        render :pdf => "ActiveAccounts", :layout => 'pdf'
      end
    end
  end

  def mail_pending
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @accounts = User.where(:expires_at => nil, :is_active => false).order('first_name asc')
      pdf = render_to_string :pdf => 'PendingAccounts',
                             :layout => 'pdf',
                             :template => 'administration/show_pending.pdf.haml'
      File.open(Rails.root.join('tmp', 'PendingAccounts.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.pending_accounts_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to account_management_path
  end

  def mail_active
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @accounts = User.where(:is_active => true).order('first_name asc')
      pdf = render_to_string :pdf => 'ActiveAccounts',
                             :layout => 'pdf',
                             :template => 'administration/show_active.pdf.haml'
      File.open(Rails.root.join('tmp', 'ActiveAccounts.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.active_accounts_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to account_management_path
  end

  def show_open
    @open = Application.admin_open(current_user).order("-departure_date desc")#.limit(6)
    @notifications = Application.admin_notification_messages(current_user).order("last_cw_note_date asc")
    respond_to do |f|
      f.html
      f.js
      f.pdf do
        if params[:view]
          render :pdf => "OpenApplications", :layout => 'pdf'
        else
          render :pdf => "OpenApplications", :layout => 'pdf', :disposition => 'attachment'
        end
      end
      f.csv do
        require 'csv'

        @open = Application.admin_open(current_user).order("-departure_date desc")
        csv = Application.generate_passengers_csv(@open)

        f = Tempfile.new 'csv'
        f << csv
        f.flush && f.rewind

        send_file f.path, :filename => 'OpenApplications.csv'
      end
    end
  end

  def show_notifications
    @notifications = Application.admin_notification_messages(current_user).order("last_cw_note_date asc").limit(6)
    @notifications += Application.admin_notification_completed(current_user).order("updated_at desc").limit(6-@notifications.size)
    @notifications.flatten!
    respond_to do |f|
      f.html
      f.js
      f.pdf do
        if params[:view]
          render :pdf => "Notifications", :layout => 'pdf'
        else
          render :pdf => "Notifications", :layout => 'pdf', :disposition => 'attachment'
        end
      end
      f.csv do
        require 'csv'

#         @notifications = Application.admin_notifications.order("last_cw_note_date asc")
        csv = Application.generate_passengers_csv(@notifications)

        f = Tempfile.new 'csv'
        f << csv
        f.flush && f.rewind

        send_file f.path, :filename => 'NotificationsExport.csv'
      end
    end
  end

  def mail_open
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @open = Application.submitted.order("updated_at asc").limit(6)
      pdf = render_to_string :pdf => 'OpenApplications',
                             :layout => 'pdf',
                             :template => 'administration/show_open.pdf.haml'
      File.open(Rails.root.join('tmp', 'OpenApplications.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.open_applications_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to application_management_path
  end

  def mail_notifications
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @notifications = Application.admin_notification_messages(current_user).order("last_cw_note_date asc").limit(6)
      @notifications += Application.admin_notification_completed(current_user).order("updated_at desc").limit(6-@notifications.size)
      @notifications.flatten!
      pdf = render_to_string :pdf => 'Notifications',
                             :layout => 'pdf',
                             :template => 'administration/show_notifications.pdf.haml'
      File.open(Rails.root.join('tmp', 'Notifications.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.notifications_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to application_management_path
  end

  def reports
  end

  def advanced
  end

  def medical_centers

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/_form.html.haml
#account-form
  = form_for @user, :html => {:class => 'bp validate'} do |f|

    %p
      = f.label :is_admin, 'Account Type:'
      = f.select :is_admin, options_for_select([['Case Worker', false], ['Administrator', true]], (@user.is_admin?))

    %p
      = f.label :first_name, "Name:"
      = f.text_field :first_name, :size => 15, :placeholder => 'First Name', :class => 'validate[required]'
      = f.text_field :last_name, :size => 15, :placeholder => 'Last Name', :class => 'validate[required]'

    %p
      = f.label :job_title, "Job Title:"
      = f.text_field :job_title, :class => 'validate[required]'

    %p
      = f.label :medical_center_id, 'Medical Center:'
      = f.select :medical_center_id, options_for_select(MedicalCenter.all.collect {|o| [o.name, o.id]},f.object.medical_center_id), {:include_blank => true}, :class => 'validate[group-org] group-org select_autocomplete'

    %p
      = f.label :organization_id, 'Organization:'
      = f.select :organization_id, options_for_select(Organization.sorted.collect{|x| [x.name, x.id]},f.object.organization_id), {:include_blank => true}, :class => 'validate[group-org] group-org select_autocomplete'

    -#
      .other-org{:class => "#{f.object.organization_id.blank? && f.object.persisted? ? '' : 'hidden'}"}

        %p
          = f.label :other_org_name, 'Organization Name:'
          = f.text_field :other_org_name, :class => 'validate[group-org] group-org'

        %p
          = f.label :other_org_abbrev, 'Organization Abbreviation:'
          = f.text_field :other_org_abbrev

        %p
          = f.label :other_org_city, 'Organization City:'
          = f.text_field :other_org_city

    %p
      = f.label :phone_1, 'Phone Number:'
      (
      = f.text_field :phone_1, 'maxLength' => 3, :class => 'phone-3 validate[required,custom[phone]]'
      )
      = f.text_field :phone_2, 'maxLength' => 3, :class => 'phone-3 validate[required,custom[phone]]'
      #{'-'}
      = f.text_field :phone_3, 'maxLength' => 4, :class => 'phone-4 validate[required,custom[phone]]'

    %p
      = f.label :email, 'E-mail Address:'
      = f.email_field :email, :class => 'validate[required,custom[email]]'

    - if f.object.persisted?
      %p
        = f.label :password, 'New Password:'
        = f.password_field :password

      %p
        = f.label :password_confirmation, 'New Password confirmation:'
        = f.password_field :password_confirmation, :class => 'validate[equals[user_password]]'

    - else
      %p
        = f.label :password, 'Password:'
        = f.password_field :password

      %p
        = f.label :password_confirmation, 'Password Confirmation:'
        = f.password_field :password_confirmation, :class => 'validate[password_required,equals[user_password]]'

    %p
      = f.label :expires_at, 'Expiration Date:'
      = f.date_select :expires_at, :start_year => Time.now.year,
                                    :end_year => Time.now.year + 10,
                                    :order => [:month, :day, :year],
                                    :include_blank => true

    %p
      = f.check_box :receive_notifications
      = f.label :receive_notifications, 'Receive Email notifications'

    .buttons
      - if f.object.persisted?
        - unless @user.is_active?
          = f.submit 'Approve', :class => 'button'
          -# = link_to 'Approve', approve_user_path(@user), :method => :post, :class => 'button'

        = f.submit 'Update', :class => 'button'

        = link_to 'Delete', user_path(@user), :method => :delete, :class => 'button'

      - else
        = f.submit 'Create!', :class => 'button'

app/views/administration/_group_applications.pdf.haml
%table
  %thead
    %tr
      %td Departing
      %td Service Member
      %td Status
      %td Created
      %td Submitted
      %td Completed

  %tbody
    - @applications.each do |a|
      %tr[a]
        %td= a.formatted_final_departure_date
        %td= a.service_member_name
        %td= a.state.capitalize
        %td= a.created_at.strftime("%m/%d/%Y")
        %td= a.formatted_submission_date
        %td= a.formatted_completion_date

app/views/administration/accounts.html.haml
#manage-accounts

  .page-title Account Management

  #pending-accounts

    .header.split
      .left Pending Accounts
      .right
        %a#export-pending-accounts{:href => '#'} PRINT/EXPORT

    %table#pending-accounts-table
      %thead
        %tr
          %td
          %td Name
          %td Medical Center / Organization
          %td Email
          %td Type
          %td Expires On

      %tbody
        - @pending.each do |u|
          %tr[u]
            %td= link_to 'view', account_path(u)
            %td= u.full_name
            %td= u.org_or_med_center_name
            %td= u.email
            %td= u.account_type
            %td= u.expires_at.blank? ? '-' : u.expires_at.strftime("%m/%d/%Y")

  #active-accounts

    .header.split
      .left Accounts
      .right
        %a#export-active-accounts{:href => '#'} PRINT/EXPORT

    #account-tools
      #search
        = form_tag '/search/accounts', :class => 'bp' do
          .split
            .left
              = link_to 'Create New Account', new_account_path, :class => 'button'
            .right
              = label_tag :q, 'Search:'
              = text_field_tag :q, params[:q], :class => 'validate[required]'
              = hidden_field_tag :status
              = hidden_field_tag :restrict

              = submit_tag 'Go!', :class => 'button'
              %br
              %a#advanced-search-link{:href => '#'} Advanced search

          #advanced_search.hidden

            %p#search_restrict
              Restrict searched fields to:
              %br
              = check_box_tag :restrict_active
              = label_tag :restrict_active, 'Active Accounts', :class => 'radio-label'

              = check_box_tag :restrict_name
              = label_tag :restrict_name, 'Name', :class => 'radio-label'

              = check_box_tag :restrict_email
              = label_tag :restrict_email, 'Email Address', :class => 'radio-label'

              = check_box_tag :restrict_phone
              = label_tag :restrict_phone, 'Phone Number', :class => 'radio-label'

            %p
              %br
              Medical Center:
              = select_tag :medical_center, options_for_select(MedicalCenter.sorted.collect{ |x| [x.name, x.id]}), :include_blank => true
            %p
              %br
              Organization:
              = select_tag :organization, options_for_select(Organization.sorted.collect{ |x| [x.name, x.id]}), :include_blank => true


    %table#active-accounts-table
      %thead
        %tr
          %td
          %td Name
          %td Medical Center / Organization
          %td Email
          %td Type
          %td Expires On

      %tbody
        - @active.each do |u|
          %tr[u]
            %td= link_to 'view', account_path(u)
            %td= u.full_name
            %td= u.org_or_med_center_name
            %td= u.email
            %td= u.account_type
            %td= u.expires_at.blank? ? '-' : u.expires_at.strftime("%m/%d/%Y")

#hidden
  #export-pending-dialog
    %p
      = link_to 'Print Application', '#', :class => 'button'

    %p
      = link_to 'Download as PDF', administration_accounts_pending_path(:pdf), :class => 'button'

    = form_tag '/administration/accounts/mail_pending', :class => 'bp validate' do
      .split
        .left
          = submit_tag 'Email as PDF', :class => 'button'
        .right
          .wrapper
            = label_tag :pdf_email_p, 'Email:'
            = email_field :pdf_email_p, '', :name => 'email', :class => 'validate[required,custom[email]]'

    %br

  #export-active-dialog
    %p
      = link_to 'Print Application', '#', :class => 'button'

    %p
      = link_to 'Download as PDF', administration_accounts_active_path(:pdf), :class => 'button'

    = form_tag '/administration/accounts/mail_active', :class => 'bp validate' do
      .split
        .left
          = submit_tag 'Email as PDF', :class => 'button'
        .right
          .wrapper
            = label_tag :pdf_email_p, 'Email:'
            = email_field :pdf_email_p, '', :name => 'email', :class => 'validate[required,custom[email]]'

    %br

app/views/administration/applications.html.haml
#applications

  .application-notice
    .notice
      %span.text
        - if AppSettings.notice
          = AppSettings.notice.gsub(/\n/,"<br/>").html_safe
        - else
          Press 'Update' to set the announcement.

      %a#update-notice.button.right{:href => '#'} Update
    .edit-notice.hidden
      - as = AppSettings.first
      = form_for as, :remote => true, :class => 'bp' do |f|
        = f.text_area :applications_notice
        = f.submit 'Save', :class => 'button'

  - if User.inactive.size > 0
    .inactive-accounts
      - if User.inactive.size == 1
        There is 1 account awaiting approval.
      - else
        There are #{User.inactive.size} accounts awaiting approval.

  #search
    = form_tag '/search/applications', :class => 'bp', :id => 'search_applications' do
      .split
        .left
          = link_to 'New Application', admin_new_application_path, :class => 'button'

        .right
          = label_tag :q, 'Search:'
          = text_field_tag :q, params[:q], :class => 'validate[required]'
          = hidden_field_tag :status, "[\"Completed\",\"Submitted\",\"Exceptions\"]" # Default status keep updated checkboxes please
          = hidden_field_tag :restrict
          = hidden_field_tag :from
          = hidden_field_tag :till
          = submit_tag 'Go!', :class => 'button'
          %br
          %a#advanced-search-link{:href => '#'} Advanced search

      #advanced_search.hidden

        Restrict by Medical Center:
        = select_tag :medical_center_id, options_for_select(MedicalCenter.sorted.collect { |x| [x.name, x.id]}), :include_blank => true

        %p
          Restrict by Organization:
          = select_tag :organization_id, options_for_select(Organization.sorted.collect { |x| [x.name, x.id]}), :include_blank => true

        %p#restrict_group
          Restrict by Group:
          = select_tag :group_id, options_for_select(Group.active.collect { |x| [x.name, x.id]}), :include_blank => true

        %p#restrict_branch
          Restrict by Branch of Service:
          = select_tag :branch, options_for_select(['Air Force', 'Army', 'Coast Guard', 'Marine Corps', 'Navy']), :include_blank => true

        %p#search_status
          Restrict searched status to:
          %br
          = check_box_tag :completed, '', true
          = label_tag :completed, 'Completed', :class => 'radio-label'

          = check_box_tag :submitted, '', true
          = label_tag :submitted, 'Submitted', :class => 'radio-label'

          = check_box_tag :exceptions, '', true
          = label_tag :exceptions, 'Exceptions', :class => 'radio-label'

          = check_box_tag :reopened, '', false
          = label_tag :reopened, 'Reopened', :class => 'radio-label'
          %br

          = check_box_tag :declined
          = label_tag :declined, 'Declined', :class => 'radio-label'

          = check_box_tag :saved, '', false
          = label_tag :saved, 'Saved', :class => 'radio-label'

          = check_box_tag :returned, '', false
          = label_tag :returned, 'Returned', :class => 'radio-label'

        %p#search_restrict
          Restrict searched fields to:
          %br
          = check_box_tag :service_member
          = label_tag :service_member, 'Service Member', :class => 'radio-label'

          = check_box_tag :passenger
          = label_tag :passenger, 'Passenger', :class => 'radio-label'

          = check_box_tag :email
          = label_tag :email, 'Email Address', :class => 'radio-label'

        %p#search_dates
          Restrict searched dates to:
          %br
          = label_tag :search_from, 'Start:'
          = date_select nil, :search_from, :order => [:month, :day, :year], :include_blank => true, :start_year => 2005, :end_year => Time.zone.now.year + 1

          = label_tag :search_till, 'End:'
          = date_select nil, :search_till, :order => [:month, :day, :year], :include_blank => true, :start_year => 2005, :end_year => Time.zone.now.year + 1

          = label_tag :date_for, 'For:'
          = select_tag :date_for, options_for_select(['Requested Departure', 'Actual Departure', 'Requested Arrival', 'Actual Arrival', 'Completed', 'Submitted', 'Exceptions', 'Declined', 'Saved', 'Returned', 'Date Booked']), :include_blank => true

        %p#search_fields
          Fields to Display:
          %br
          = check_box_tag :field_departing, 'field_departing', true
          = label_tag :field_departing, 'Departing', :class => 'radio-label'

          = check_box_tag :field_service_member, 'field_service_member', true
          = label_tag :field_service_member, 'Service Member', :class => 'radio-label'

          = check_box_tag :field_status, 'field_status', true
          = label_tag :field_status, 'Status', :class => 'radio-label'

          = check_box_tag :field_created, 'field_created', true
          = label_tag :field_created, 'Created', :class => 'radio-label'
          %br

          = check_box_tag :field_submitted, 'field_submitted'
          = label_tag :field_submitted, 'Submitted', :class => 'radio-label'

          = check_box_tag :field_completed, 'field_completed', true
          = label_tag :field_completed, 'Date Booked', :class => 'radio-label'

          = check_box_tag :field_case_worker, 'field_case_worker', true
          = label_tag :field_case_worker, 'Case Worker', :class => 'radio-label'

          = check_box_tag :field_medical_center, 'field_medical_center', true
          = label_tag :field_medical_center, 'Medical Center', :class => 'radio-label'

        %p.submit
          = submit_tag 'Go!', :class => 'button'


  - unless @notifications.empty?
    #notifications.admin

      .header.split
        .left Case Worker Inquiries/Comments
        .right
          %a#export-notifications{:href => '#'} PRINT/EXPORT

      = render 'administration/notifications'

  #open-applications.admin

    .header.split
      .left Open Applications
      .right
        %a#export-open-applications{:href => '#'} PRINT/EXPORT

    = render 'administration/open_applications'

#hidden
  #checkout-dialog

    %h3 Check Out Application?
    %p
      This application has already been checked out by
      %span.admin-name

    .buttons
      %a.checkout-button.button{:href => '#'} Check Out
      %a.view-button.button{:href => '#'} View Only


  #export-open-dialog
    %table
      %tbody
        %tr
          %td
            Open Applications (PDF)
          %td
            %a#view-export-link{:href => administration_applications_open_path(:view => 'true', :format => 'pdf') } view
          %td
            %a#save-export-link{:href => administration_applications_open_path(:save => 'true', :format => 'pdf') } save
        - if current_user.is_admin?
          %tr
            %td
              All Data (CSV)
            %td
            %td
              %a#save-all-data-link{:href => administration_applications_open_path(:format => 'csv')} save

  #export-notifications-dialog
    %table
      %tbody
        %tr
          %td
            Notifications (PDF)
          %td
            %a#view-export-link{:href => administration_applications_notifications_path(:view => 'true', :format => :pdf) } view
          %td
            %a#save-export-link{:href => administration_applications_notifications_path(:save => 'true', :format => :pdf) } save
        - if current_user.is_admin?
          %tr
            %td
              All Data (CSV)
            %td
            %td
              %a#save-all-data-link{:href => administration_applications_notifications_path(:format => 'csv')} save

app/views/administration/show_group.html.haml
#show-group

  .page-title #{@group.name} Group Application Entry


  %a.button{:href => admin_new_application_path(:group => @group.id), :id => 'add-app-btn'} Add an Application

  .header.split
    .left Applications
    .right
      %a#export-applications{:href => '#'} PRINT/EXPORT

  = render 'administration/group_applications'

  = paginate @applications

#hidden
  #export-applications-dialog
    %p
      = link_to 'Print Application', '#', :class => 'button'

    %p
      = link_to 'Download as PDF', show_group_path(:format => :pdf, :id => params[:id], :page => params[:page]), :class => 'button'

    = form_tag mail_group_path(:id => params[:id], :page => params[:page]), :class => 'bp validate' do
      .split
        .left
          = submit_tag 'Email as PDF', :class => 'button'
        .right
          .wrapper
            = label_tag :pdf_email_p, 'Email:'
            = email_field :pdf_email_p, '', :name => 'email', :class => 'validate[required,custom[email]]'

    %br