config/routes.rb
HeroMiles::Application.routes.draw do

  match "/administration" => 'administration#index', :as => 'admin_home'
  match "/administration/applications" => 'administration#applications', :as => 'application_management'
  match '/administration/applications/new' => 'administration#new_application', :as => 'admin_new_application'
  match '/administration/applications/open' => 'administration#show_open'
  match '/administration/applications/notifications' => 'administration#show_notifications'
  match '/administration/applications/:id' => 'administration#show_application', :as => 'admin_show_application'
  match '/administration/organizations' => 'administration#organizations', :as => 'organization_management'
  match '/administration/medical_centers' => 'administration#medical_centers', :as => 'medical_center_management'
  match '/administration/airports' => 'administration#airports', :as => 'airport_management'
  match '/administration/airlines' => 'administration#airlines', :as => 'airline_management'
  match '/administration/groups' => 'administration#groups', :as => 'group_management'
  match '/administration/groups/new' => 'administration#new_group', :as => 'new_group'
  match '/administration/groups/:id/edit' => 'administration#edit_group', :as => 'edit_group'
  match '/administration/groups/:id/mail' => 'administration#mail_group', :as => 'mail_group'
  match '/administration/groups/:id' => 'administration#show_group', :as => 'show_group'
  match '/administration/settings' => 'administration#settings', :as => 'settings'
  match '/administration/attachments' => 'administration#attachments', :as => 'attachments'

  match '/administration/accounts' => 'administration#accounts', :as => 'account_management'
  match '/administration/accounts/pending' => 'administration#show_pending'
  match '/administration/accounts/mail_pending' => 'administration#mail_pending'
  match '/administration/accounts/mail_active' => 'administration#mail_active'
  match '/administration/accounts/active' => 'administration#show_active'
  match '/administration/accounts/new' => 'administration#new_account', :as => 'new_account'
  match '/administration/accounts/:id' => 'administration#show_account', :as => 'account'

  match '/administration/reports' => 'administration#reports', :as => 'report_management'
  match '/administration/advanced' => 'administration#advanced', :as => 'advanced_management'

  match "/case_worker" => 'case_worker#index', :as => 'case_worker_home'

  match '/case_worker/applications' => 'case_worker#applications', :as => 'case_worker_applications'
  match '/case_worker/applications/new' => 'case_worker#new_application', :as => 'case_worker_new_application'
  match '/case_worker/applications/open' => 'case_worker#show_open'
  match '/case_worker/applications/notifications' => 'case_worker#show_notifications'
  match '/case_worker/applications/:id' => 'case_worker#show_application', :as => 'case_worker_show_application'

  match '/case_worker/accounts' => 'case_worker#accounts', :as => 'case_worker_accounts'
  match '/case_worker/reports' => 'case_worker#reports', :as => 'case_worker_reports'
  match '/case_worker/groups' => 'case_worker#groups', :as => 'case_worker_groups'
  match '/case_worker/groups/:id/mail' => 'case_worker#mail_group', :as => 'case_worker_mail_group'
  match '/case_worker/groups/:id' => 'case_worker#show_group', :as => 'case_worker_show_group'

  match '/search/applications' => 'search#applications', :as => 'applications_search'
  match '/search/accounts' => 'search#accounts', :as => 'accounts_search'

  match '/sign_up_confirmation' => 'home#sign_up_confirmation'

  devise_for :users, :controllers => {:registrations => 'registrations',
                                      :sessions => 'sessions' } do
    get 'sign_in', :to => 'sessions#new', :as => 'sign_in'
    get 'sign_out', :to => 'devise/sessions#destroy', :as => 'sign_out'
  end

  resources :users, :path => 'accounts', :only => [:create, :update, :destroy] do
    member do
      post 'approve'
    end
  end

  resources :applications do
    member do
      get 'checkout'
      get 'checkin'
      get 'reopen'
      get 'export'
      post 'mail'
    end
    collection do
      get 'airport'
    end
  end

  resources :application_notes, :only => :create

  resources :organizations, :medical_centers, :airports, :airlines, :groups do
    member do
      post 'archive'
      post 'unarchive'
    end
  end

  resources :app_settings, :only => [:create, :update] do
    collection do
      post 'new_category'
      post 'remove_category'
      post 'update_category'
    end
  end

  match '/reports/summary' => 'reports#summary', :as => 'summary_report'
  match '/reports/monthly' => 'reports#monthly', :as => 'monthly_report'
  match '/reports/branch_airline' => 'reports#branch', :as => 'branch_report'

  root :to => 'home#index'

end

app/views/shared/_footer.html.haml
#footer
  111 Rockville Pike, Suite 420 | Rockville, Maryland 20850 | (888) 294-8560 | &copy; #{Time.zone.now.year} Fisher House&trade; Foundation, Inc.

app/views/shared/_header.html.haml
#header-wrapper
  #header
    .tag-line
      %a{:href => 'http://fisherhouse.org'}
        = image_tag 'tag_line.png'
    .logo
      = image_tag 'logo.png'

    -# FIXME - Very messy, clean it up.

    - if user_signed_in?
      #header-nav.nav
        %ul
          - if current_user.is_admin?
            %li
              %a.first{:href => application_management_path, :class => "#{ 'selected' if ['applications', 'show_application', 'new_application'].include?(controller.action_name)}" } APPLICATIONS
            %li
              %a{:href => account_management_path, :class => "#{ 'selected' if (['accounts', 'new_account', 'show_account'].include?(controller.action_name) || controller.controller_name == 'registrations')}" } ACCOUNTS
            %li
              %a{:href => report_management_path, :class => "#{ 'selected' if controller.action_name == 'reports' || controller.controller_name == 'reports'}" } REPORTS
            %li.last
              %a{:href => group_management_path, :class => "#{ 'selected' if ['groups', 'new_group', 'show_group', 'edit_group', 'medical_centers', 'airlines', 'settings', 'organizations', 'airports', 'attachments'].include?(controller.action_name)}" } ADVANCED
          - else
            %li
              %a.first{:href => case_worker_applications_path, :class => "#{ 'selected' if ['applications', 'new_application', 'show_application'].include?(controller.action_name)}" } APPLICATIONS
            %li
              %a{:href => case_worker_accounts_path, :class => "#{ 'selected' if (controller.action_name == 'accounts' || controller.controller_name == 'registrations')}" } ACCOUNT
            %li
              %a{:href => case_worker_reports_path, :class => "#{ 'selected' if controller.action_name == 'reports'}" } REPORTS
            %li.last
              %a{:href => case_worker_groups_path, :class => "#{ 'selected' if ['groups', 'show_group'].include?(controller.action_name)}" } ADVANCED

  - if user_signed_in?
    - if ((controller.controller_name == 'administration' && controller.action_name == 'accounts') || (controller.controller_name == 'registrations'))
      #header-sub-nav.nav
        - if current_user.is_admin?
          %a{:href => account_management_path, :class => "#{ 'selected' if controller.action_name == 'accounts'}"} Account Management
        %a{:href => edit_user_registration_path(current_user), :class => "#{ 'selected' if controller.controller_name == 'registrations'}"} Update Information
        %a.last{:href => sign_out_path } Sign Out
    - elsif ['groups', 'show_group', 'edit_group', 'new_group', 'airlines', 'medical_centers', 'settings', 'organizations', 'airports', 'attachments'].include?(controller.action_name)
      #header-sub-nav.nav
        - if current_user.is_admin?
          %a{:href => group_management_path, :class => "#{ 'selected' if ['groups', 'new_group', 'show_group', 'edit_group'].include?(controller.action_name)}"} Groups
          %a{:href => organization_management_path, :class => "#{ 'selected' if controller.action_name == 'organizations'}"} Organizations
          %a{:href => medical_center_management_path, :class => "#{ 'selected' if controller.action_name == 'medical_centers'}"} Medical Centers
          %a{:href => airline_management_path, :class => "#{ 'selected' if controller.action_name == 'airlines'}"} Airlines
          %a{:href => airport_management_path, :class => "#{ 'selected' if controller.action_name == 'airports'}"} Airports
          %a{:href => attachments_path, :class => "#{ 'selected' if controller.action_name == 'attachments'}"} Attachments
          %a.last{:href => settings_path, :class => "#{ 'selected' if controller.action_name == 'settings'}"} Miscellaneous
        - else
          %a.last{:href => case_worker_groups_path, :class => "#{ 'selected' if ['groups', 'show_group'].include?(controller.action_name)}"} Groups