config/routes.rb
HeroMiles::Application.routes.draw do

  match "/administration" => 'administration#index', :as => 'admin_home'
  match "/administration/applications" => 'administration#applications', :as => 'application_management'
  match '/administration/applications/new' => 'administration#new_application', :as => 'admin_new_application'
  match '/administration/applications/open' => 'administration#show_open'
  match '/administration/applications/notifications' => 'administration#show_notifications'
  match '/administration/applications/:id' => 'administration#show_application', :as => 'admin_show_application'
  match '/administration/organizations' => 'administration#organizations', :as => 'organization_management'
  match '/administration/medical_centers' => 'administration#medical_centers', :as => 'medical_center_management'
  match '/administration/airports' => 'administration#airports', :as => 'airport_management'
  match '/administration/airlines' => 'administration#airlines', :as => 'airline_management'
  match '/administration/groups' => 'administration#groups', :as => 'group_management'
  match '/administration/groups/new' => 'administration#new_group', :as => 'new_group'
  match '/administration/groups/:id/edit' => 'administration#edit_group', :as => 'edit_group'
  match '/administration/groups/:id/mail' => 'administration#mail_group', :as => 'mail_group'
  match '/administration/groups/:id' => 'administration#show_group', :as => 'show_group'
  match '/administration/settings' => 'administration#settings', :as => 'settings'
  match '/administration/attachments' => 'administration#attachments', :as => 'attachments'

  match '/administration/accounts' => 'administration#accounts', :as => 'account_management'
  match '/administration/accounts/pending' => 'administration#show_pending'
  match '/administration/accounts/mail_pending' => 'administration#mail_pending'
  match '/administration/accounts/mail_active' => 'administration#mail_active'
  match '/administration/accounts/active' => 'administration#show_active'
  match '/administration/accounts/new' => 'administration#new_account', :as => 'new_account'
  match '/administration/accounts/:id' => 'administration#show_account', :as => 'account'

  match '/administration/reports' => 'administration#reports', :as => 'report_management'
  match '/administration/advanced' => 'administration#advanced', :as => 'advanced_management'

  match "/case_worker" => 'case_worker#index', :as => 'case_worker_home'

  match '/case_worker/applications' => 'case_worker#applications', :as => 'case_worker_applications'
  match '/case_worker/applications/new' => 'case_worker#new_application', :as => 'case_worker_new_application'
  match '/case_worker/applications/open' => 'case_worker#show_open'
  match '/case_worker/applications/notifications' => 'case_worker#show_notifications'
  match '/case_worker/applications/:id' => 'case_worker#show_application', :as => 'case_worker_show_application'

  match '/case_worker/accounts' => 'case_worker#accounts', :as => 'case_worker_accounts'
  match '/case_worker/reports' => 'case_worker#reports', :as => 'case_worker_reports'
  match '/case_worker/groups' => 'case_worker#groups', :as => 'case_worker_groups'
  match '/case_worker/groups/:id/mail' => 'case_worker#mail_group', :as => 'case_worker_mail_group'
  match '/case_worker/groups/:id' => 'case_worker#show_group', :as => 'case_worker_show_group'

  match '/search/applications' => 'search#applications', :as => 'applications_search'
  match '/search/accounts' => 'search#accounts', :as => 'accounts_search'

  match '/sign_up_confirmation' => 'home#sign_up_confirmation'

  devise_for :users, :controllers => {:registrations => 'registrations',
                                      :sessions => 'sessions' } do
    get 'sign_in', :to => 'sessions#new', :as => 'sign_in'
    get 'sign_out', :to => 'devise/sessions#destroy', :as => 'sign_out'
  end

  resources :users, :path => 'accounts', :only => [:create, :update, :destroy] do
    member do
      post 'approve'
    end
  end

  resources :applications do
    member do
      get 'checkout'
      get 'checkin'
      get 'reopen'
      get 'export'
      post 'mail'
    end
    collection do
      get 'airport'
    end
  end

  resources :application_notes, :only => :create

  resources :organizations, :medical_centers, :airports, :airlines, :groups do
    member do
      post 'archive'
      post 'unarchive'
    end
  end

  resources :app_settings, :only => [:create, :update] do
    collection do
      post 'new_category'
      post 'remove_category'
      post 'update_category'
    end
  end

  match '/reports/summary' => 'reports#summary', :as => 'summary_report'
  match '/reports/monthly' => 'reports#monthly', :as => 'monthly_report'
  match '/reports/branch_airline' => 'reports#branch', :as => 'branch_report'

  root :to => 'home#index'

end

app/controllers/case_worker_controller.rb
class CaseWorkerController < ApplicationController
  before_filter :authenticate_user!

  def index
    redirect_to case_worker_applications_path
  end

  def applications
    @open = current_user.applications.open_applications.limit 10
    @notifications = current_user.applications.cw_notifications.order('updated_at desc').limit current_user.notifications_count(30)
  end

  def new_application
    @application = Application.new :user => current_user, :organization => current_user.organization
#     if current_user.organization
#       @group = current_user.organization.groups.find_by_id params[:group]
#     else
#       @group = nil
#     end
    @group = (params[:group] ? Group.find_by_id(params[:group]) : nil )
    if @group
      @application.group = @group
      @application.set_group_defaults
    end
    @application.set_cw_details
    AppSettings.first.max_passengers.times { |x| @application.application_passengers.build }
    AppSettings.attachment_categories.select { |x| !x['admin'] && x['cw'] && x['required'] && !x['is_archived'] }.each do |ac|
      @application.attachments.build :is_cw => true,
                                     :is_required => true,
                                     :category => ac['name'],
                                     :ref_id => ac['id']
    end
    @medical_centers = MedicalCenter.sorted
    @organizations = Organization.sorted
  end

  def show_application
    if current_user.organization_id || current_user.medical_center_id
      @application =  Application.find_by_id_and_case_worker_organization_id(params[:id], current_user.organization_id) if current_user.organization_id
      @application = Application.find_by_id_and_case_worker_medical_center_id(params[:id], current_user.medical_center_id) if current_user.medical_center_id
    else
      @application = current_user.applications.find_by_id params[:id]
    end
    redirect_to '/404' and return if @application.blank?
    if @application.is_editable?(current_user)
      (AppSettings.first.max_passengers - @application.application_passengers.size).times { |x| @application.application_passengers.build}
      AppSettings.attachment_categories.select { |x| !x['admin'] && x['cw'] && x['required'] && !x['is_archived'] }.each do |ac|
        attachment = @application.attachments.find_by_ref_id ac['id']
        if attachment.blank?
          @application.attachments.build :is_cw => true,
                                        :is_required => true,
                                        :category => ac['name'],
                                        :ref_id => ac['id']
        end
        end
    end

    @medical_centers = MedicalCenter.sorted
    @organizations = Organization.sorted

    respond_to do |f|
      f.html
      f.pdf { render :pdf => "Application-#{@application.id}", :layout => 'pdf'}
    end
  end

  def show_open
    @open = current_user.applications.open_applications.limit(10)
    respond_to do |f|
      f.html
      f.js
      f.pdf do
        if params[:view]
          render :pdf => "OpenApplications", :layout => 'pdf'
        else
          render :pdf => "OpenApplications", :layout => 'pdf', :disposition => 'attachment'
        end
      end
    end
  end

  def show_notifications
    @notifications = current_user.applications.cw_notifications.order('updated_at desc').limit current_user.notifications_count(30)
    respond_to do |f|
      f.html
      f.js
      f.pdf do
        if params[:view]
          render :pdf => "Notifications", :layout => 'pdf'
        else
          render :pdf => "Notifications", :layout => 'pdf', :disposition => 'attachment'
        end
      end
    end
  end

  def mail_open
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @open = current_user.applications.open_applications.limit(6)
      pdf = render_to_string :pdf => 'OpenApplications',
                             :layout => 'pdf',
                             :template => 'case_worker/show_open.pdf.haml'
      File.open(Rails.root.join('tmp', 'OpenApplications.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.open_applications_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to case_worker_applications_path
  end

  def mail_notifications
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @notifications = current_user.applications.cw_notifications.order('last_admin_note_date desc').limit(6)
      pdf = render_to_string :pdf => 'Notifications',
                             :layout => 'pdf',
                             :template => 'case_worker/show_notifications.pdf.haml'
      File.open(Rails.root.join('tmp', 'Notifications.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.notifications_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = "Email not sent. Please enter a valid email"
    end
    redirect_to case_worker_applications_path
  end

  def accounts
    redirect_to edit_user_registration_path
  end

  def reports
  end

  def groups
  end

  def show_group
    @group = Group.find_by_id params[:id]
    @applications = current_user.applications.where(:group_id => @group.id).order('created_at asc').page(params[:page]).per(11)
    respond_to do |f|
      f.html
      f.pdf do
        render :pdf => 'GroupApplications', :layout => 'pdf'
      end
    end
  end

  def mail_group
    if params[:email] && !(params[:email] =~ /.+@.+\..+/).nil?
      @group = Group.find_by_id params[:id]
      @applications = current_user.applications.where(:group_id => @group.id).order('created_at asc').page(params[:page]).per(11)

      pdf = render_to_string :pdf => 'GroupApplications',
                             :layout => 'pdf',
                             :template => 'case_worker/show_group.pdf.haml'
      File.open(Rails.root.join('tmp', 'GroupApplications.pdf'), 'wb') do |f|
        f << pdf
      end
      begin
        AppMailer.group_applications_email(params[:email]).deliver
        flash[:notice] = 'Email sent successfully'
      rescue
        flash[:alert] = AppSettings.invalid_credentials_message
      end
    else
      flash[:alert] = 'Email not sent. Please enter a valid email'
    end
    redirect_to case_worker_show_group_path(@group)
  end

end

app/helpers/case_worker_helper.rb
module CaseWorkerHelper
end

app/views/case_worker/_group_applications.html.haml
%table
  %thead
    %tr
      %td
      %td Departing
      %td Service Member
      %td Status
      %td Created
      %td Submitted
      %td Completed

  %tbody
    - @applications.each do |a|
      %tr[a]
        %td
          %a{:href => case_worker_show_application_path(a)} view
        %td= a.formatted_final_departure_date
        %td= a.service_member_name
        %td= a.state.capitalize
        %td= a.created_at.strftime("%m/%d/%Y")
        %td= a.formatted_submission_date
        %td= a.formatted_completion_date

app/views/case_worker/_group_applications.pdf.haml
%table
  %thead
    %tr
      %td Departing
      %td Service Member
      %td Status
      %td Created
      %td Submitted
      %td Completed

  %tbody
    - @applications.each do |a|
      %tr[a]
        %td= a.formatted_final_departure_date
        %td= a.service_member_name
        %td= a.state.capitalize
        %td= a.created_at.strftime("%m/%d/%Y")
        %td= a.formatted_submission_date
        %td= a.formatted_completion_date

app/views/case_worker/_notifications.html.haml
%table#notifications-table
  %thead
    %tr
      %td
      %td Departure Date
      %td Service Member
      %td Status
      %td Admin Note

  %tbody
    - @notifications.each do |n|
      %tr[n]{:class => "#{(!n.has_note?) ? '' :((n.last_note_by_admin?)? 'admin-note' : 'case-worker-note') } "}
        %td
          %a{:href => case_worker_show_application_path(n)} view
        %td= n.formatted_final_departure_date
        %td= n.service_member_name
        %td= n.state.capitalize
        %td= n.formatted_admin_note_date

app/views/case_worker/_notifications.pdf.haml
#notifications-table
  %table
    %thead
      %tr
        %td Departure Date
        %td Service Member
        %td Status
        %td Admin Note

    %tbody
      - @notifications.each do |n|
        %tr{:class => cycle('odd', 'even')}
          %td= n.formatted_final_departure_date
          %td= n.service_member_name
          %td= n.state.capitalize
          %td= n.formatted_admin_note_date

app/views/case_worker/new_application.html.haml
#new-application
  .page-title New Application
  = render 'applications/form'

app/views/case_worker/reports.html.haml
#reports

  .page-title Reports

  .header Available Reports

  %table
    %thead
      %tr
        %td Options
        %td Report Name

    %tbody
      %tr
        %td
          %a{:href => AppSettings.first.blank_application.url } view

        %td Printable Blank Application
#hidden

  #upload-blank-dialog
    %h4 Upload a printable blank application:

    = form_for AppSettings.first, :html => {:class => 'bp'} do |as|

      = as.file_field :blank_application
      = as.submit 'Upload'
      = hidden_field_tag :blank_application, true

  #summary-dialog
    %h4 Please set the following date range:

    = form_tag '/reports/summary', :class => 'bp validate' do

      .wrapper
        = label_tag :year_from, 'Start Year:'
        = select_tag :year_from, options_for_select(2008..Time.now.year), :include_blank => true, :class => 'validate[required]'

      .wrapper
        = label_tag :year_till, 'End Year:'
        = select_tag :year_till, options_for_select(2008..Time.now.year), :include_blank => true, :class => 'validate[required]'

      .wrapper
        = label_tag :medical_center, 'Medical Center:'
        = select_tag :medical_center, options_for_select(MedicalCenter.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .wrapper
        = label_tag :organization, 'Organization:'
        = select_tag :organization, options_for_select(Organization.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .buttons
        = submit_tag 'Generate Report', :class => 'button'

  #monthly-dialog
    = form_tag '/reports/monthly', :class => 'bp validate' do

      .wrapper
        = label_tag :med_monthly, 'Medical Center:'
        = select_tag :med_monthly, options_for_select(MedicalCenter.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .wrapper
        = label_tag :org_monthly, 'Organization:'
        = select_tag :org_monthly, options_for_select(Organization.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .buttons
        = submit_tag 'Generate Report', :class => 'button'

  #branch-dialog
    %h4 Please set the following parameters:

    = form_tag '/reports/branch_airline', :class => 'bp validate' do

      .wrapper
        = label_tag :branch, 'Branch or Airline'
        %br

        = radio_button_tag :branch, 'branch', true
        = label_tag :branch_branch, 'Branch of Service'
        %br
        = radio_button_tag :branch, 'airline'
        = label_tag :branch_airline, 'Airline'

      .wrapper
        = label_tag :type, 'Tickets or Savings or Miles'
        %br

        = radio_button_tag :type, 'ticket', true
        = label_tag :type_ticket, 'Ticket'
        %br

        = radio_button_tag :type, 'savings'
        = label_tag :type_savings, 'Savings'
        %br

        = radio_button_tag :type, 'miles'
        = label_tag :type_miles, 'Miles'
        %br

      .wrapper
        = label_tag :year, 'Year'
        %br

        = select_tag :year, options_for_select(2008..Time.now.year)

      .wrapper
        = label_tag :med, 'Medical Center'
        %br
        = select_tag :med, options_for_select(MedicalCenter.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .wrapper
        = label_tag :org, 'Organization'
        %br
        = select_tag :org, options_for_select(Organization.sorted.collect { |x| [x.name, x.id]}), :prompt => 'All'

      .buttons
        = submit_tag 'Generate Report', :class => 'button'

app/views/case_worker/show_application.html.haml
#show-application

  .page-title View Application

  .top-notice
    - notes = @application.application_notes.order('created_at desc')
    = render :partial => 'application_notes/note', :locals => {:n => notes.first}
  - if notes.size > 1
    %a#toggle-application-history{:href => '#'} [+] Show History
    #application-notes.hidden
      - notes[1, notes.size - 1].each do |an|
        = render :partial => 'application_notes/note', :locals => {:n => an}

  = render 'applications/form'

app/views/case_worker/show_group.html.haml
#show-group

  .page-title #{@group.name} Group Application Entry


  %a.button{:href => case_worker_new_application_path(:group => @group.id)} Add an Application

  .header.split
    .left Applications
    .right
      %a#export-applications{:href => '#'} PRINT/EXPORT

  = render 'case_worker/group_applications'

  = paginate @applications

#hidden
  #export-applications-dialog
    %p
      = link_to 'Print Application', '#', :class => 'button'

    %p
      = link_to 'Download as PDF', case_worker_show_group_path(:format => :pdf, :id => params[:id], :page => params[:page]), :class => 'button'

    = form_tag case_worker_mail_group_path(:id => params[:id], :page => params[:page]), :class => 'bp validate' do
      .split
        .left
          = submit_tag 'Email as PDF', :class => 'button'
        .right
          .wrapper
            = label_tag :pdf_email_p, 'Email:'
            = email_field :pdf_email_p, '', :name => 'email', :class => 'validate[required,custom[email]]'

    %br

app/views/case_worker/show_group.pdf.haml
= render 'case_worker/group_applications'

app/views/case_worker/show_notifications.js.erb
$("#notifications table").fadeOut().replaceWith("<%= escape_javascript(render('case_worker/notifications')) %>").fadeIn();

app/views/case_worker/show_notifications.pdf.haml
= render 'case_worker/notifications'

app/views/case_worker/show_open.js.erb
$("#open-applications table").fadeOut().replaceWith("<%= escape_javascript(render('case_worker/open_applications')) %>").fadeIn();